export const revenueData = [
  { month: "Jan", revenue: 12500, users: 450 },
  { month: "Feb", revenue: 18200, users: 620 },
  { month: "Mar", revenue: 22100, users: 780 },
  { month: "Apr", revenue: 19800, users: 690 },
  { month: "May", revenue: 28400, users: 920 },
];

export const userGrowthData = [
  { month: "Jan", active: 2400, new: 400 },
  { month: "Feb", active: 3200, new: 600 },
  { month: "Mar", active: 4100, new: 750 },
  { month: "Apr", revenue: 3800, new: 580 },
  { month: "May", active: 5200, new: 880 },
];

export const subscriptionData = [
  { name: "Free", value: 65, color: "#8884d8" },
  { name: "Pro", value: 25, color: "#82ca9d" },
  { name: "Premium", value: 10, color: "#ffc658" },
];

export const courses = [
  {
    id: 1,
    title: "Digital Art Fundamentals",
    description: "Learn the basics of digital art creation",
    instructor: "Sarah Johnson",
    category: "Fundamentals",
    level: "Beginner",
    duration: "8 weeks",
    price: 199,
    enrolled: 1250,
    rating: 4.8,
    status: "Published",
    thumbnail: "/placeholder.svg?height=200&width=300",
    modules: [
      {
        id: 1,
        title: "Introduction to Digital Art",
        type: "video",
        duration: "45 min",
        completed: 95,
      },
      {
        id: 2,
        title: "Setting Up Your Workspace",
        type: "video",
        duration: "30 min",
        completed: 87,
      },
      {
        id: 3,
        title: "Basic Tools and Brushes",
        type: "interactive",
        duration: "60 min",
        completed: 78,
      },
      {
        id: 4,
        title: "Color Theory Assignment",
        type: "assignment",
        duration: "2 hours",
        completed: 65,
      },
    ],
  },
  {
    id: 2,
    title: "Advanced Portrait Painting",
    description: "Master the art of realistic portrait painting",
    instructor: "Michael Chen",
    category: "Advanced",
    level: "Advanced",
    duration: "12 weeks",
    price: 399,
    enrolled: 680,
    rating: 4.9,
    status: "Published",
    thumbnail: "/placeholder.svg?height=200&width=300",
    modules: [
      {
        id: 1,
        title: "Anatomy for Artists",
        type: "video",
        duration: "90 min",
        completed: 92,
      },
      {
        id: 2,
        title: "Light and Shadow",
        type: "video",
        duration: "75 min",
        completed: 85,
      },
      {
        id: 3,
        title: "Skin Tones and Textures",
        type: "interactive",
        duration: "120 min",
        completed: 71,
      },
      {
        id: 4,
        title: "Final Portrait Project",
        type: "assignment",
        duration: "5 hours",
        completed: 58,
      },
    ],
  },
  {
    id: 3,
    title: "Abstract Art Exploration",
    description: "Discover your unique abstract style",
    instructor: "Emma Rodriguez",
    category: "Contemporary",
    level: "Intermediate",
    duration: "6 weeks",
    price: 149,
    enrolled: 890,
    rating: 4.6,
    status: "Draft",
    thumbnail: "/placeholder.svg?height=200&width=300",
    modules: [
      {
        id: 1,
        title: "Understanding Abstract Art",
        type: "video",
        duration: "40 min",
        completed: 0,
      },
      {
        id: 2,
        title: "Color and Emotion",
        type: "video",
        duration: "35 min",
        completed: 0,
      },
      {
        id: 3,
        title: "Composition Techniques",
        type: "interactive",
        duration: "50 min",
        completed: 0,
      },
    ],
  },
];

export const recentUsers = [
  {
    id: 1,
    name: "Emma Rodriguez",
    email: "emma@email.com",
    plan: "Pro",
    joined: "2024-05-20",
    status: "Active",
  },
  {
    id: 2,
    name: "Marcus Chen",
    email: "marcus@email.com",
    plan: "Premium",
    joined: "2024-05-19",
    status: "Active",
  },
  {
    id: 3,
    name: "Sofia Williams",
    email: "sofia@email.com",
    plan: "Free",
    joined: "2024-05-18",
    status: "Inactive",
  },
  {
    id: 4,
    name: "David Kumar",
    email: "david@email.com",
    plan: "Pro",
    joined: "2024-05-17",
    status: "Active",
  },
];

export const quizzes = [
  {
    id: 1,
    title: "Color Theory Basics",
    category: "Fundamentals",
    participants: 1250,
    avgScore: 78,
    status: "Active",
  },
  {
    id: 2,
    title: "Renaissance Masters",
    category: "Art History",
    participants: 890,
    avgScore: 82,
    status: "Active",
  },
  {
    id: 3,
    title: "Digital Art Techniques",
    category: "Modern",
    participants: 2100,
    avgScore: 71,
    status: "Draft",
  },
  {
    id: 4,
    title: "Composition Rules",
    category: "Fundamentals",
    participants: 1680,
    avgScore: 85,
    status: "Active",
  },
];

export const challenges = [
  {
    id: 1,
    title: "30-Day Sketch Challenge",
    participants: 3400,
    prize: "$500",
    endDate: "2024-06-15",
    status: "Active",
  },
  {
    id: 2,
    title: "Abstract Art Contest",
    participants: 1200,
    prize: "$300",
    endDate: "2024-06-30",
    status: "Active",
  },
  {
    id: 3,
    title: "Portrait Week",
    participants: 890,
    prize: "$200",
    endDate: "2024-05-30",
    status: "Ended",
  },
  {
    id: 4,
    title: "Landscape Photography",
    participants: 2100,
    prize: "$400",
    endDate: "2024-07-10",
    status: "Upcoming",
  },
];
